# Test against the latest version of this Node.js version
environment:
  matrix:
    # node.js
    - nodejs_version: "9"
  COVERALLS_REPO_TOKEN:
    secure: 77iTlGmCE6TK9dPwYG0jZeejC9JNKHRZPZVD/1Fsh9w+4d7LDyUOFdRXM0DR1tGc

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  - npm install --save-dev jasmine
  - ./node_modules/.bin/jasmine init
  - npm install --save-dev jasmine-xml-reporter
  #- npm install --save-dev coveralls
  - npm install --save-dev karma
  - npm install --save-dev karma-coverage

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  # npm test
  #- ./node_modules/.bin/jasmine
  - node ./node_modules/jasmine-xml-reporter/bin/jasmine.js --junitreport --output=./testresults
  #- node ./node_modules/jasmine-xml-reporter/bin/jasmine.js --junitreport
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./testresults/results.xml))
  - ps: $temp = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./testresults/results.xml)
  - ps: Write-Host "$temp"

after_test:
  #- node ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info 
  #- ./node_modules/.bin/istanbul cover --report lcov ./node_modules/.bin/jasmine
  - ./node_modules/.bin/istanbul cover --report lcov ./node_modules/jasmine/bin/jasmine.js
  
# Don't actually build.
build: off
